### ISSUE TITLE
Understanding user classes

### ISSUE THREAD

**Issue by t3db0t** [logpy/logpy#52]
I'm struggling a bit with user classes.  I have this script: https://gist.github.com/t3db0t/2f31e4bcb103a168563b657ea510ee1c

The unification works, and I get the expected result (finding a device with a certain ID).  *However*, when it prints out, I see that if the 'dummy' value is the same as any property values, those values all get overridden to the search value.

So this is fixable by providing a dummy value that would 'never' occur, but that's sketchy.  I also am not quite clear on exactly what function the dummy values are performing?  Like, why can't I just do `source = Controller(0x0)` and `target = Controller(0x0)` and leave out the `with variables(*vars)`?

**Comment by t3db0t** [comment]
Is it because the unifier is going to use those values to 'identify' pseudo-logvars?

Also, regardless, the example should add a little explanation of this ;)

**Comment by lucaswiman** [comment]
The bug is that you're attempting to reify the Python literal `0` as though it were a variable. This has some weird effects, since it means that it replaces _other_ instances of `0` with the value it unified to the id (`0xABCD` in this case). You can make your code work correctly if you replace `dummyId = 0` with `dummyId = var('dummyID')` and get rid of the `with variables` context.

I think it isn't really feasible to make the `variables` context manager work correctly in python, and even for strings it can have the same weird effects, like renaming an attribute if it happens to have the same as a variable on a class. It should probably be removed from the `unification` API for this reason.

**Comment by t3db0t** [comment]
Gotcha—`var('something')` seems to be working nicely.  I basically copied this all from the `user_classes.py` example.

In that example, it says "variables are arbitrary Python objects, not kanren Var objects":
https://github.com/logpy/logpy/blob/master/examples/user_classes.py#L12-L18

I'd be happy to update this example in a PR unless I'm misunderstanding.

**Comment by lucaswiman** [comment]
> In that example, it says "variables are arbitrary Python objects, not kanren Var objects":

Yeah, I think it makes sense to deprecate that idea, since it lead to very counterintuitive bugs like this.

> I'd be happy to update this example in a PR unless I'm misunderstanding.

That would be greatly appreciated.

**Comment by t3db0t** [comment]
Also, similarly, we should document the use of a parameter with `var()`

**Comment by t3db0t** [comment]
I think I'm confusing myself—how is naming a `var` different than not? Currently I have things like:
```
dummyId = var('dummyID')
dummyRelay = var('dummyRelay')
dummyDimLevel = var('dummyDimLevel')
source = Controller(dummyId, dummyRelay, dummyDimLevel)
```
Is this different than just making them each `= var()`? Can I just do `newDummyId, newDummyRelay, newDummyDimLevel = vars(3)`?

**Comment by lucaswiman** [comment]
They're the same; it just makes debugging output a bit nicer.

**Comment by t3db0t** [comment]
Gotcha—ok.
