### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by daishi** [logpy/logpy#63]
Invoking `python setup.py install` in a otherwise vanilla Python virtualenv (2.7.13) results in:
```
Processing dependencies for kanren==0.2.3
Searching for unification
Reading https://pypi.python.org/simple/unification/
Downloading https://pypi.python.org/packages/1c/26/432ea4a47aded7b0d64662fc265252da2b2a059f92af2eeb3321d60c9f8a/unification-0.2.2.tar.gz#md5=b2f1723d75b0f5c34a7e9be4137eafbf
Best match: unification 0.2.2
Processing unification-0.2.2.tar.gz
Writing /var/folders/gj/_4b9jvwj1qg2vcv231xvz5sr0000gq/T/easy_install-qGiQjt/unification-0.2.2/setup.cfg
Running unification-0.2.2/setup.py -q bdist_egg --dist-dir /var/folders/gj/_4b9jvwj1qg2vcv231xvz5sr0000gq/T/easy_install-qGiQjt/unification-0.2.2/egg-dist-tmp-O8KXW2
error: [Errno 2] No such file or directory: 'dependencies.txt'
```
(On Mac OS X)

**Comment by lucaswiman** [comment]
This appears to be a bug in [`unification`](https://github.com/mrocklin/unification), not in this repository. If you run `pip install unification` prior to running `python setup.py install` it fixes the immediate issue. The bug seems to be that `unification` is missing a manifest that adds dependencies.txt, so setup.py is trying to read from a file which is not present.
